baseURL = 'https://cmyzk-git.github.io/value-trace/'
languageCode = 'ja'
title = 'Value Trace'
theme = 'blowfish'

[params]
  chart = true
# これがないと、外部（Amazon）の画像をサムネイルとして使えません
  externalImage = true 
  
  # 念のため、カードビューの設定も確認してください
  [params.homepage]
    cardView = true
    cardThumbnail = true


