baseURL = 'https://cmyzk-git.github.io/value-trace/'
languageCode = 'ja'
title = 'Value Trace'
theme = 'PaperMod'

[params]
  env = "production"
  title = "Value Trace"
  description = "商品価格推移アーカイブ"
  
  # 記事一覧で画像を表示するための設定
  showFullContents = false
  displayFullContent = false
  
  # グラフ(Chart.js)を有効にする
  chart = true

[params.cover]
  responsiveImages = false # 外部URL画像を使用するためオフにする
  linkFullImages = true
