baseURL = 'https://cmyzk-git.github.io/value-trace/'
languageCode = 'ja'
title = 'Value Trace'
theme = 'blowfish'

[params]
  chart = true
  externalImage = true 
  referrerPolicy = "no-referrer" # ここが最重要です

[params.article]
  showFeatured = true
  showThumbnail = true
  # 外部サイトの画像を記事のアイキャッチとして使う許可
  externalImages = true # 's' がついていることを確認
  # 外部画像（Amazon等）のブロックを回避するための設定
  referrerPolicy = "no-referrer"
  showFeatured = true
  showThumbnail = true



# hugo.toml のどこかにこれがあるか確認
[params.homepage]
  showRecent = true
  showRecentItems = 10
  layout = "card"
  cardView = true
  cardThumbnail = true
  showSummary = true




