baseURL = "https://cmyzk-git.github.io/value-trace/"
languageCode = "ja"
title = "Value Trace"
theme = "blowfish"

[params]
  chart = true

[params.homepage]
  showRecent = true
  showRecentItems = 5
  layout = "background"

# どのフォルダ（posts）を表示するかを指定します
[main]
  sections = ["posts"]

[markup.goldmark.renderer]
  unsafe = true