baseURL = 'https://cmyzk-git.github.io/value-trace/'
languageCode = 'ja'
title = 'Value Trace'
theme = 'blowfish'

[params]
  chart = true
  externalImage = true # これはそのまま

[params.article]
  showFeatured = true
  showThumbnail = true
  # 外部サイトの画像を記事のアイキャッチとして使う許可
  externalImages = true 

[params.homepage]
  layout = "card"
  cardView = true
  cardThumbnail = true
  showSummary = true
