baseURL = "https://cmyzk-git.github.io/value-trace/"
languageCode = "ja"
title = "Value Trace"
theme = "blowfish"

# ここから下を追加・上書きしてください
[params]
  chart = true

[taxonomies]
  category = "categories"
  tag = "tags"

[markup.goldmark.renderer]
  unsafe = true