baseURL = 'https://cmyzk-git.github.io/value-trace/'
languageCode = 'ja'
title = 'Value Trace'
theme = 'blowfish'

[params]
  chart = true
  # 重要：外部サイトの画像を許可する設定
  externalImage = true

[params.homepage]
  layout = "card"
  # 重要：カード形式でサムネイルを表示する設定
  cardView = true
  cardThumbnail = true


